### ISSUE TITLE
Improve imports

### ISSUE THREAD

**Issue by navalpatel384** [lgarron/clipboard-polyfill#100]
`import clipboard from 'clipboard-polyfill'` is not always compatible with newer projects that have to use an import statement like `import * as clipboard from 'clipboard-polyfill'` or 
`import { clipboard } from clipboard-polyfill`.

**Comment by lgarron** [comment]
> import { clipboard } from clipboard-polyfill

There is no `clipboard` field on anything exported, so I don't think this could ever work. Is there something I'm missing?

> newer projects that have to use an import statement like `import * as clipboard from 'clipboard-polyfill'`

Every time I look into this, I get really frustrated with the state of Javascript module compatibility. My understanding is that based on how you're doing this, either of `import clipboard from 'clipboard-polyfill'` or `import * as clipboard from 'clipboard-polyfill'` might work or fail, but the former is ""the right way" to import a default export.

If there's a way I can export a single value that:
- works with the same import statement everywhere, and
- that does not break backwards compatibility,
I'd love to use that.

(Note that I don't consider it a good solution to add a `clipboard` member on `ClipboardPolyfill` referencing itself. 😕)

**Comment by navalpatel384** [comment]
I agree that module compatibility can sometimes be frustrating. My project only supports ES2015 imports and it depends on copy to clipboard being available in all browsers. The previous version of the project works fine with clipboard-polyfill but the new version in development requires that it can be imported with either 
`import { IMPORTNAME } from 'clipboard-polyfill'` 
or 
`import * as clipboard from 'clipboard-polyfill'`.

Is there another build tool that clipboard-polyfill can use that would be backwards compatible and support ES2015 imports?

**Comment by lgarron** [comment]
See https://github.com/lgarron/clipboard-polyfill/issues/77#issuecomment-432518818
