### ISSUE TITLE
Change from the default export to the full export object

### ISSUE THREAD

**Issue by lgarron** [lgarron/clipboard-polyfill#101]
As of v2.7.0, the intended way to use `clipboard-polyfill` will be:

    import * as clipboard from "clipboard-polyfill"
    // ...
    clipboard.writeText("hi!")

Or:

    const clipboard = require("clipboard-polyfill")

This replaces the old convention of the `default` export:

    // Old – do not use unless your environment requires it
    import clipboard from "clipboard-polyfill"

In some environments, `import *` worked previously. However, I believe this change will be compatible with more environments/build systems. Hopefully that will address #77.

If you use the `default` export, then there is a compatibility shim will still work in `v2.7.0` but will print a warning. I plan to drop support for the `default` export in `v3.0.0`. Please comment here if you believe this will introduce an incompatibility for you, ideally with a link to a repo with a full repro case.

**Comment by lgarron** [comment]
Note: I was originally planning to do this in a `v3.0.0` release, but this is now published as `v2.7.0` because it should be backwards-compatible in most environments.

The `default` export will be removed in `v3.0.0`.

**Comment by Favna** [comment]
If anything `import * as` versus `import default from` would be covered by TypeScript with ESModuleInterop afaik - and to be frank not using ESModuleInterop does developers more harm in issues to address than good. Way too many JS based libs that just don't export ES6 / TS friendly and basically require the compiler flag. 

Aside from that, when following the semantic versioning spec it should be perfectly okay to include breaking changes in major version changes so you as a lib developer shouldn't be fussed about creating such as long as you change the major version. It is up to implementors (like me in the future perhaps 🤔) to be wary of major version upgrades - and preferebly install with the ^version spec.

**Comment by Livven** [comment]
I agree with @Favna, `esModuleInterop` should work fine and is also necessary for many other packages, e.g. `react` (and `create-react-app` sets it by default).

From what I understand Babel also handles it automatically and the convention for most packages indeed seems to be `import default` (or `import { explicit }`) rather than `import * as`, so I hope you can reconsider this change.

**Comment by lgarron** [comment]
As of v3.0.0, there's no default export any more!
