### ISSUE TITLE
Async/await firefox error

### ISSUE THREAD

**Issue by doglasbatista** [lgarron/clipboard-polyfill#102]
Hi, 

I'm receiving the following error message on firefox 60.3.0esr version: 
`document.execCommand('cut'/'copy') was denied because it was not called from inside a short running user-generated event handler.`

This is a sample of what I'm trying to do

```
import clipboard from 'clipboard-polyfill'

const response = await axios.get('/api/path')
clipboard.writeText(response)
```

I'm using clipboard-pollyfill 2.7.0 version

This code works as intended on google chrome 70.0.3538.77 version

**Comment by lgarron** [comment]
As the error message says, Firefox requires the clipboard API to be called inside a short-running event handler. `await axios.get('/api/path')` can be a relatively long round-trip. Chrome has a bit of a leniency period, but it will also fail on slow connections to your server.

The best option is either to prepare the data ahead of time, or show a messages to the user that you are preparing the data and asking them to trigger another action to actually copy the data.

See https://github.com/w3c/clipboard-apis/issues/41 for proposals to handle delayed clipboard data in the future.
