### ISSUE TITLE
TypeScript TypeError on global.Navigator.clipboard with lib: ["esnext", "dom"]

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [lgarron/clipboard-polyfill#106]
In `clipboard-polyfill.d.ts`, `global.Navigator.clipboard` has optional members:

```ts
clipboard: {
    writeText?: (s: string) => Promise<void>;
    readText?: () => Promise<string>;
};
```

...but in `lib.dom.d.ts`, it's of type `Clipboard` with non-optional members:

```ts
interface Clipboard extends EventTarget {
    readText(): Promise<string>;
    writeText(data: string): Promise<void>;
}
```

Raw VS Code error here:

```json
{
	"resource": "/Code/Project/node_modules/clipboard-polyfill/build/clipboard-polyfill.d.ts",
	"owner": "typescript",
	"code": "2687",
	"severity": 8,
	"message": "All declarations of 'clipboard' must have identical modifiers.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 9,
	"endLineNumber": 4,
	"endColumn": 18
}
```

Edit: I managed to work around this by adding a `./clipboard-polyfill.d.ts` with no contents to the project. That works because TypeScript will give up trying to find the backing typings file for a `import * as clipboard from "clipboard-polyfill";` as soon as it finds one. Run `tsc --traceDiagnostics` to see the paths it looks at before finding this project's typings.

**Comment by lgarron** [comment]
I just pushed the latest version: #105. Let me know if that works!

**Comment by JoshuaKGoldberg** [comment]
Oh, coming back to this, yes 😄 it does fix it. Thanks so much for the quick turnaround!
