### ISSUE TITLE
Unhandled Promise Rejection: Copy command failed

### ISSUE THREAD

**Issue by philgyford** [lgarron/clipboard-polyfill#107]
Maybe I've missed something or done something wrong, but...

I have a page in which I've included `build/clipboard-polyfill.promise.js`. On a Mac (10.14.4), in desktop Chrome (73.0.3683), if I go into the console I can do `clipboard.writeText("Copy me")` and it works.

But, using desktop Safari (12.1) or Firefox (66.0.3), doing the same thing, I get "Unhandled Promise Rejection: Copy command failed." (Safari) or "uncaught exception: Copy command failed." (FF).

![Screenshot 2019-04-24 at 12 00 53](https://user-images.githubusercontent.com/66670/56654706-a0bf7c80-6688-11e9-9a0f-163b16b4f55d.png)

**Comment by lgarron** [comment]
Unfortunately, there is no browser standard about exactly what counts as a user gesture. Chrome actually [allows commands from the console to consume a user gesture](https://bugs.chromium.org/p/chromium/issues/detail?id=593241), but I presume other browsers don't.

This should only affect direct invocations from the console, and not interactions with the page. Libraries can't do anything about it.
