### ISSUE TITLE
Update read and write to use new ClipboardItem

### ISSUE THREAD

**Issue by opusonline** [lgarron/clipboard-polyfill#113]
Hi!

Your polyfill is great!
I really liked your early implementation of `read` and `write` using `DataTransfer` and I know that this is even mentioned in the Explainer (https://github.com/w3c/clipboard-apis/blob/master/explainer.adoc#writing-to-the-clipboard) but the current implementation of Chrome is now using `Array<ClipboardItem>` objects as you can see here (https://developers.google.com/web/updates/2019/07/image-support-for-async-clipboard#images).

Please let me know if you want further information.

Best regards,
Stefan

**Comment by lgarron** [comment]
This is fantastic! I'd like to support it as soon as possible. :-D

**Comment by lgarron** [comment]
This is implemented in `v3.0.0`! (I've published a few pre-releases.)
