### ISSUE TITLE
Promise Polyfill not working

### ISSUE THREAD

**Issue by itsmhuang** [lgarron/clipboard-polyfill#116]
This import is no longer working `import * as clipboard from "clipboard-polyfill/build/clipboard-polyfill.promise"` 

I checked the directory, and did not see a 'build' folder, but saw a 'dist' folder. Changed path to that. Worked again. Was directory changed recently?

Version: 2.8.4

**Comment by lgarron** [comment]
Yeah, I accidentally messed up the order of releases leading up to `v3.0.0`. :-(

`clipboard-polyfill/dist/clipboard-polyfill.promise` *should* work.

**Comment by itsmhuang** [comment]
Ok I have temporarily changed it to that.

**Comment by lgarron** [comment]
Okay, the old import should continue to work in `v2.8.5`. However, I recommend using `clipboard-polyfill/build/clipboard-polyfill.promise`, since that will be the path in `v3`!

**Comment by lgarron** [comment]
> Okay, the old import should continue to work in `v2.8.5`.

Make that `v2.8.6`, which actually has the relevant files in the published package.

**Comment by itsmhuang** [comment]
@lgarron thank you!
