### ISSUE TITLE
Stopped working with Safari 13.0.1 (Mac OS 10.14.6) -> [Error] Unhandled Promise Rejection

### ISSUE THREAD

**Issue by picov** [lgarron/clipboard-polyfill#119]
Version 2.8.0 and 2.8.5 worked well with Safari 12.1.1 (MacOS 10.14.6).
With the last Safari major update v13.0.1 I got the error below into the console and no text is copied into the os clipboard (Chrome v 67 and Firefox v69 works with the same code).

[Error] Unhandled Promise Rejection: Error: Copy command failed.
	(funzione anonima) (clipboard-polyfill.promise.js:1:4691)
	(funzione anonima) (clipboard-polyfill.promise.js:1:3673)
	initializePromise
	Promise
	e (clipboard-polyfill.promise.js:1:3465)
	copyToClipboard (bookings_list.php:6329)
	newEmail (bookings_list.php:6370)
	success (bookings_list.php:7405)
	c (jquery.min.js:2:27748)
	fireWith (jquery.min.js:2:28489)
	l (jquery.min.js:2:78801)
	(funzione anonima) (jquery.min.js:2:81119)
	send
	send (jquery.min.js:2:81481)
	ajax (jquery.min.js:2:77300)
	createEmailMessage (bookings_list.php:7392)
	(funzione anonima) (bookings_list.php:6837)
	dispatch (jquery.min.js:2:42577)

**Comment by lgarron** [comment]
https://garron.net/code/clipboard-polyfill/ is using the `clipboard-polyfill.promise.js ` version and it still works for me in Safari 13.0.1 on macOS 10.14.6.

Your stack trace implies that you're making a server round-trip before copying the data. Browsers usually require you do copy immediately in response to a user action if you want it to work reliable. Could you check if copying something directly from `createEmailMessage()` works?

**Comment by picov** [comment]
Yes, direct copy works in Safari 13.0.1.
The problem seems that I get the content to copy from an AJAX request fired by a button click.

I need to set "async: false" in JQuery Ajax options in order to make the copy works in Firefox and Safari 12.x (Chrome not need this) in order to avoid that the call "exit" from the button click event handler, but with Safari 13.x this trick not works anymore.

**Comment by lgarron** [comment]
> A synchronous AJAX request keep the clipboard operations inside the button click event handler, but with Safari 13.x this trick not works anymore.

Indeed, most browsers expect you to copy directly in response to a user gesture, and you should expect the copy operation to fail if you introduce any significant delay.

There's nothing that a library can do to help with this, although I recommend keeping up with the new clipboard API developments for potential delayed copy operations.

The simplest workaround for situations like yours (if it's truly impractical to generate immediately) is to use a button to generate/retrieve the relevant data, and then offer a second operation to actually copy it.
