### ISSUE TITLE
Is it possible to copy the base64 images

### ISSUE THREAD

**Issue by BattiniSantthosh** [lgarron/clipboard-polyfill#121]

**Comment by lgarron** [comment]
Could you provide an example of what you mean?

I suspect the answer is no, but there is probably a simple conversion step that would work to copy it like a normal image (where possible).

**Comment by avrahamzvv** [comment]
im looking the same, it need to be saved like "text/html "
but in type needs to be "image"

this is how i paste but i don't know how copy

var items = (e.clipboardData  || e.originalEvent.clipboardData).items;
    for (var i = 0; i < items.length; i++) {
      if (items[i].type.indexOf("image") === 0) {
        blob = items[i].getAsFile();
      }
    }
var reader = new FileReader();
      reader.onload = function(event) {
        var i = new Image(); 
        //event.target.result    //image
}
