### ISSUE TITLE
Can clipboard-polyfill support read and paste screenshot image?

### ISSUE THREAD

**Issue by kagol** [lgarron/clipboard-polyfill#123]

**Comment by avrahamzvv** [comment]
var rhtml = e.clipboardData.getData('text/html');
    var rplain = e.clipboardData.getData('text/plain');
    var items = (e.clipboardData  || e.originalEvent.clipboardData).items;
    for (var i = 0; i < items.length; i++) {
      if (items[i].type.indexOf("image") === 0) {
        blob = items[i].getAsFile();
        fimg = 1;
      }
    }

     if (blob !== null && fimg==1) {
      var reader = new FileReader();
      reader.onload = function(event) {
        var i = new Image(); 
        i.onload = function(){
          //alert( i.width+", "+i.height );
           var src = event.target.result
           //paste img here
        };
        i.src = event.target.result; 
     };
      reader.readAsDataURL(blob);

**Comment by kagol** [comment]
Thank you for your proposal.
But can clipboardData.items support the old browser version(Like Chrome 56 browser)?

**Comment by lgarron** [comment]
With version v3.0.0, `clipboard-polyfill` can read PNG files in browser that have support.
