### ISSUE TITLE
clipboard in Safari 

### ISSUE THREAD

**Issue by theYllwRvrNo98** [lgarron/clipboard-polyfill#125]
in Safari
` clipboard.writeText("coped!")`
it worked

```
 axios.post("url").then(() => {
                    clipboard.writeText("cccc");
                });
```
it not worked

**Comment by awreccan** [comment]
From the README:
> Browsers may require a user gesture or user permission to access the clipboard. In particular, you should write text only in response to an event listener, e.g. a button click listener.

**Comment by lgarron** [comment]
> From the README:
> 
> > Browsers may require a user gesture or user permission to access the clipboard. In particular, you should write text only in response to an event listener, e.g. a button click listener.

Indeed, this is something that a polyfill cannot address.
