### ISSUE TITLE
Firefox doesn't support readText

### ISSUE THREAD

**Issue by dvkndn** [lgarron/clipboard-polyfill#129]
Hi, thank for the great library!

I'm using Firefox (75) and the "paste" function doesn't work:

![Screenshot from 2020-05-02 14-18-22](https://user-images.githubusercontent.com/5953369/80857902-cf9b0600-8c7f-11ea-9113-bed18607a962.png)

I'm not sure if this is the expected behavior and I should handle it myself. Afaik it's because Firefox does have the `navigator.clipboard` object but in non-extension context it only has writeText but no readText:

![Screenshot from 2020-05-02 14-15-31](https://user-images.githubusercontent.com/5953369/80857923-f9ecc380-8c7f-11ea-9b2d-275ab83c6575.png)

Ref: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#Browser_compatibility

> Notes Firefox only supports reading the clipboard in browser extensions, using the "clipboardRead" extension permission.

Do you think clipboard-polyfill should fallback to another mechanism to handle the read in Firefox? Like what you did with IE

Thank you

**Comment by lgarron** [comment]
> Do you think clipboard-polyfill should fallback to another mechanism to handle the read in Firefox? Like what you did with IE

Unfortunately, there is no way to work around it. I'll have to wait until Firefox adds support.

**Comment by lgarron** [comment]
I should add that I don't want to add any workarounds that modify the shapre of the API. We could add a text box to the page telling the user to paste, but that is outside the scope of this library.
