### ISSUE TITLE
The new import syntax breaks builds

### ISSUE THREAD

**Issue by dmitrizzle** [lgarron/clipboard-polyfill#133]
`Module not found: Can't resolve 'clipboard-polyfill/text' in '/Users/.../app'`

Tried to use the fancy new export but unfortunately not able to. With:
- `webpack@4.43.0`
- within the project build with `next@9.4.4`

**Comment by lgarron** [comment]
Looks like the `/text` folder wasn't included in the build. This should be fixed in v3.0.1.
