### ISSUE TITLE
Include Flat-file version with Promise included

### ISSUE THREAD

**Issue by jamieburchell** [lgarron/clipboard-polyfill#134]
Please include the flat file version in the repo/npmjs (and the referenced .map file).

Since this plugin provides functionality for old browsers, it would be really useful not to have to transpile and build the source, and instead be able to simply `npm i` this package and have the flat file/dist version available to copy from `node_modules`

**Comment by lgarron** [comment]
It's already in the published package: https://unpkg.com/browse/clipboard-polyfill@3.0.1/dist/promise/clipboard-polyfill.promise.js

Are you unable to use it from there?

**Comment by jamieburchell** [comment]
My mistake. I wrongly assumed that if the file was not provided in the repo and that a direct link was provided to the flat file elsewhere, that it would not be available after an `npm i`. Sorry about that.

**Comment by lgarron** [comment]
> My mistake. I wrongly assumed that if the file was not provided in the repo and that a direct link was provided to the flat file elsewhere, that it would not be available after an `npm i`. Sorry about that.

No worries; happy coding!
