### ISSUE TITLE
Safari 14.0 / Paste text not working

### ISSUE THREAD

**Issue by wesleymostien** [lgarron/clipboard-polyfill#137]
On [https://garron.net/code/clipboard-polyfill/](https://garron.net/code/clipboard-polyfill/) the 'paste text' option throws this error :

'NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. '

How to implement pasting in Safari?

**Comment by lgarron** [comment]
Hmm, I'm having no issue with Safari 14 on iOS or macOS. Could you provide more details about how you're running into this error?

**Comment by lgarron** [comment]
@wesleymostien I'm closing this issue for now. If you can still identify a bug, feel free to comment or open a new issue with more details!
