### ISSUE TITLE
Throw error when writetext at in-app browser on Android device

### ISSUE THREAD

**Issue by nonren** [lgarron/clipboard-polyfill#138]
Hi all, I'm facing issue at in-app browser on android device. 

NonAllowedError: Write permission denied.

It working fine on iOS device. But doesn't work on android device.

Any idea for this?

**Comment by lgarron** [comment]
Unfortunately, Chrome Custom Tabs doesn't seem to allow interacting with the clipboard. :-/
This is the same issue as #118, so I'm gonna close fold this issue into that one.

I think your best chance of getting this fixed is to file an issue on the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/entry

**Comment by lgarron** [comment]
> Unfortunately, Chrome Custom Tabs doesn't seem to allow interacting with the clipboard. :-/
> This is the same issue as #118, so I'm gonna close fold this issue into that one.
> 
> I think your best chance of getting this fixed is to file an issue on the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/entry

Sorry about this, I was testing wrong. This is a known issue with Facebook apps, not Chrome Custom Tabs. Which app are you facing issues with?
