### ISSUE TITLE
Safari 13+ Unhandled Promise Rejection: 

### ISSUE THREAD

**Issue by Bielykh-Artem** [lgarron/clipboard-polyfill#139]
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

**Comment by lgarron** [comment]
Could I ask you to provide the full context on how you're getting this error?
In particular, did you make the request in the top frame in direct response to a user gesture (e.g. a button press)?

**Comment by lgarron** [comment]
@Bielykh-Artem I'm closing this issue for now. If you can still identify a bug, feel free to comment or open a new issue with more details!
