### ISSUE TITLE
import `overwrite-globals` not working

### ISSUE THREAD

**Issue by jhukdev** [lgarron/clipboard-polyfill#140]
I need to apply the global polyfill as we load a js file seperately on older browsers to reduce unnecessary code.

The [docs here](https://www.npmjs.com/package/clipboard-polyfill#overwrite-globals-version) mention `import 'clipboard-polyfill/overwrite-globals';` to do it, but it's not resolving this:

```
Module not found: Error: Can't resolve 'clipboard-polyfill/overwrite-globals'
```

Is there something I'm missing?

Thanks in advance for any help!

**Comment by lgarron** [comment]
Hmm, looks like the `overwrite-globals` folder is not on the published lib. I'll have to fix that.

**Comment by lgarron** [comment]
Let me know if v3.0.2 works for you!

> I need to apply the global polyfill as we load a js file seperately on older browsers to reduce unnecessary code.

Generally, I would suggest using an async `import()` for this (polyfilled into a script include if needed), but I understand not everyone has the tooling to make that work smoothly in older browsers.

**Comment by jhukdev** [comment]
@lgarron Perfect, yes works like a charm! 

> Generally, I would suggest using an async import()

In our case we serve a "legacy" and "modern" bundle in ES5 and ES7 respectively, using the "Differential Loading" pattern to only serve to clients that support either. Our polyfill file is handled in a similar way. Handling it via `import()` would be better, but muddies our code base with support conditionals, and our IE11 user base is tiny!

Many thanks for sorting this out, one less thing for me to worry about! 👍
