### ISSUE TITLE
Remove linebreak in the richtext format

### ISSUE THREAD

**Issue by khoivan88** [lgarron/clipboard-polyfill#142]
Hi, Thank you very much for this useful library. 

I have a quick question on the use of copy rich text format of DOM nodes, it seems that this library adds a line break between `<div>`? At least base on my test case. 

For example, this is my div that I want to be copy into clipboard with rich text format:
```html
<div id="10.1021acs.chemrev.0c01282">
  <div class="csl-bib-body">
    <div data-csl-entry-id="temp_id_6016270873906286" class="csl-entry">
      <div class="csl-left-margin">Shieh, P.; Hill, M. R.; Zhang, W.; Kristufek, S. L.; Johnson, J. A. </div><div class="csl-right-inline"><b>Clip Chemistry: Diverse (Bio)(Macro)Molecular and Material Function through Breaking Covalent Bonds</b>. <i>Chem. Rev.</i> <b>2021</b>.</div>
      <be>
      <a href="https://doi.org/10.1021/acs.chemrev.0c01282" class="underline text-info" target="_blank" rel="noopener">
          https://doi.org/10.1021/acs.chemrev.0c01282
      </a>
    </div>
  </div>
</div>
```

JS function:
```js
// https://github.com/lgarron/clipboard-polyfill
import * as clipboard from 'clipboard-polyfill';

async function copyCitationToClipBoard() {
  // Get the id of the div containing the bib using the div#id
  // div#id is in the form of 'copy-doi' with 'doi' being slugify by 11ty
  const regexCitationId = /copy-(.*)/g;
  let citationId = regexCitationId.exec(this.id)[1];
  // console.log(citationId);

  // Get citation div
  const bibItem = document.getElementById(`${citationId}`);

  // Remove all more than 2 white spaces (\n, \t, etc)
  const regexMoreThanTwoWhitespace = /\s{2,}|<br\s*\/*>/g;
  const bibContent = (new XMLSerializer().serializeToString(bibItem)).replace(regexMoreThanTwoWhitespace, '');

  const blobRtf = new Blob([bibContent], { type: 'text/html' });
  const blobPlain = new Blob([bibContent], { type: 'text/plain' });
  const items = [
    new clipboard.ClipboardItem({
      'text/html': blobRtf,
      'text/plain': blobPlain,
    }),
  ];
  clipboard.write(items);
}

window.addEventListener('DOMContentLoaded', function () {
  document
    .querySelectorAll('.citation-copy-btn').forEach(function (btn) {
      btn.addEventListener('click', copyCitationToClipBoard);
    })
});
```

Notably is the line break when pasted into Words or other text editor: `<div class="csl-left-margin">Shieh, P.; Hill, M. R.; Zhang, W.; Kristufek, S. L.; Johnson, J. A. </div><div class="csl-right-inline"><b>Clip Chemistry: Diverse (Bio)(Macro)Molecular and Material Function through Breaking Covalent Bonds</b>. <i>Chem. Rev.</i> <b>2021</b>.</div>`

I was just wondering if you might have any suggestion for me to remove this line break in the rich text format in the clipboard. As you can see above, I tried to remove any excess line breaks with the regex and can confirm the result after `new XMLSerializer().serializeToString` but that still did not help!

Thank you very much!

**Comment by lgarron** [comment]
`navigator.clipboard` now supports `text/html` in Safari. Could you try that to see if it works any better?

**Comment by lgarron** [comment]
> ```js
>   document
>     .querySelectorAll('.citation-copy-btn').forEach(function (btn) {
>       btn.addEventListener('click', copyCitationToClipBoard);
>     })
> ```

The example HTML doesn't have any button with the class `citation-copy-btn`. Could I ask for a more complete example?
