### ISSUE TITLE
Does not work with SvelteKit in production mode

### ISSUE THREAD

**Issue by benmccann** [lgarron/clipboard-polyfill#143]
I received the error:
```
To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
```

SvelteKit is based on Vite, so this probably affects all Vite SSR users

**Comment by lgarron** [comment]
Could you let me know if `v4.0.0-rc3` fixes your issue?

**Comment by lgarron** [comment]
> "type": "module" in the package.json

This is now the case, so I'm going to speculatively close this are resolved.
