### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by plztrial4me** [lgarron/clipboard-polyfill#147]
When I jues used the sample code in Typescript, I got an error "Blob is not defined".

How can I solve that?

--

 import * as clipboard from "clipboard-polyfill";

const item = new clipboard.ClipboardItem({
        "text/html": new Blob(["<i>Markup</i> <b>text</b>. Paste me into a rich text editor."], { type: "text/html" }),
        "text/plain": new Blob(["Fallback markup text. Paste me into a rich text editor."], { type: "text/plain" }),
    });
await clipboard.write([item]);

**Comment by lgarron** [comment]
Could you provide more details about your environment?

`Blob` is available almost everywhere: https://caniuse.com/?search=Blob

Is it possible that something else is unsetting `globalThis.Blob`?
