### ISSUE TITLE
polifill deprecation: too early

### ISSUE THREAD

**Issue by marcoromag** [lgarron/clipboard-polyfill#149]
Hi,

just FYI: Firefox still does not support ClipboardItem, therefore this polyfill is still required... :(

BR,
Marco

**Comment by lgarron** [comment]
> Hi,
> 
> just FYI: Firefox still does not support ClipboardItem, therefore this polyfill is still required... :(
> 
> BR, Marco

Ah, yeah, looks like you're right, I totally forgot it was behind a flag. 😭

Are you using `ClipboardItem` for `text/html`?
(If not, then a polyfill can't do anything for you.)

**Comment by aduth** [comment]
Another consideration may be JSDOM support, common part of testing stacks.

Related: https://github.com/jsdom/jsdom/issues/1568

**Comment by am05mhz** [comment]
also, in your readme, navigator.clipboard.writeText() is listed as supported on major browsers

**Comment by JounQin** [comment]
`navigator.clipboard` is only available in HTTPS, we migrate these days, and is causes `clipboard` is HTTP environment for our business customers...

**Comment by lgarron** [comment]
> `navigator.clipboard` is only available in HTTPS, we migrated these days, and it caused `clipboard` error in HTTP environments for our business customers...

That's good to know!
Business websites should definitely be using HTTPS in 2022, and browsers might drop polyfill compat for HTTP anyhow; is there any chance of supporting HTTPS for the relevant sites?

**Comment by JounQin** [comment]
There are a lot of internal websites using IPs as domain + HTTP directly by our business customers.

**Comment by lgarron** [comment]
I'm working on putting the codebase into maintenance mode — no new features, but I'll try to keep it working as long as possible.
