### ISSUE TITLE
NextJS + clipboard-polyfill version 4 bug

### ISSUE THREAD

**Issue by unwls** [lgarron/clipboard-polyfill#160]
Hey, thanks for such an amazing library!

Just wanted to drop by to let you know about the current issue with NextJS and the clipboard-polyfill library.

After your update 8 hours ago, deploying through GitHub action kept failing with the below error.

<img width="660" alt="Screen Shot 2023-01-05 at 10 38 12 PM" src="https://user-images.githubusercontent.com/83770081/210792896-0faa07b6-20b4-4a1a-a1f2-da47702ab2b8.png">

After removing the clipboard-polyfill dependency, everything worked as it should.

Please let me know if you know why the new update is causing this error when using NextJS. 

FYI Haven't tried client side rendering yet.

**Comment by lgarron** [comment]
Could you let me know more details about where in `clipboard-polyfill` is erroring?

**Comment by lgarron** [comment]
Ah, I think I might have it — the new code always tries to use `window` to get a reference to the `Promise` constructor. I'll fix that.

**Comment by lgarron** [comment]
Could you let me know if `v4.0.0-rc5` works for you?
