### ISSUE TITLE
[ENHANCEMENT]: Use document.getSelection() and the copy and cut events to implement readText() in Firefox v63.x+

### ISSUE THREAD

**Issue by isocroft** [lgarron/clipboard-polyfill#163]
I would like to propose that this package polyfills `Clipbaord.prototype.readText` as follows (rough implementation):

```javascript
/* @HNIT: Feature Detection: If the browser is a Gecko-based browser (e.g. Firefox) */
if (typeof window.InstallTrigger !== "undefined") {
    if (typeof Clipboard.prototype.readText !== "text") {
     /* @NOTE: Firefox v62.x+ natively supports `DataTransfer()` constructor */
      const dataTransfer = new DataTransfer();
    
      document.addEventListener('copy', handleTextCapture);
      document.addEventListener('cut', handleTextCapture);
    
      function handleTextCapture (event) {
          const textCaptureTarget = event.target;
          const activeElement = document.activeElement;
          
          if (activeElement !== null) {
             if (textCaptureTarget.contains(activeElement) || textCaptureTarget === activeElement) {
               const selection = document.getSelection();
               if (
                 selection !== null
                   && typeof activeElement.selectionEnd === "number"
                     && typeof activeElement.selectionStart === "number") {
                 event.clipboardData.setData('text/plain', selection.toString());
                 dataTransfer.setData('text/plain', selection.toString());
              }
           }
        }
      }
      
      Object.defineProperty(Clipboard.prototype, "readText", {
         writable: false,
          value: () => {
              const clipboardData = dataTransfer.getData('text/plain');
              if (clipboardData) {
                 return Promise.resolve(clipboardData);
              }
              return Promise.reject(new Error("No data on clipboard"));
          }
       });
    }
 }
```

**Comment by lgarron** [comment]
Could you elaborate on what your goal is?

From what I can tell, the snippet you've posted just handles a parallel plain text clipboard within the page itself and contains several assumptions and restrictions that are not explained.

**Comment by isocroft** [comment]
Hey @lgarron , So my goal is to not have to create a separate polyfill for `Clipboard.prototype.readText` in Firefox v63+ which doesn't natively implement `readText()` but does implement `writeText()`. This has often been a pin point for me especially when developing dashboard web apps. 

Therefore, I felt it was going to be much more expedient to implement the polyfill in this package as it already has some of the basic boilerplate code (as it is already a polyfill package) need to build up a solution for Firefox v63+. I can't tell you how many times an error from error monitoring/tracking software has filled my error batches with errors from Firefox about not supporting `readText()` and i have to implement weird hack/workarounds to support users on Firefox.

Also, the code snippet i wrote above (like i mentioned) is a rough implementation. I do plan to write the code more extensively to use `Storage` (`window.localStorage`) events to ensure cross-page synchronisation of the quasi-`dataTransfer` ("`clipboardData`") object. 

In this rough implementation, i don't take care of the assumption however i recognise them. I wouldd need some time to share a proper implementation here.

Thank you very much for the opportunity to establish my intent more clearly.

**Comment by lgarron** [comment]
Hi @isocroft,

That sounds like it could be useful for some sites, but wouldn't actually interact with the system clipboard at all. That kind of functionality is completely outside the scope of `clipboard-polyfill`, although you'd be welcome to develop it as a separate library.

**Comment by isocroft** [comment]
@lgarron okay, no problem. Thanks a lot for your time 🙏🏾
