### ISSUE TITLE
`overwrite-globals` build triggers a memory leak in Firefox

### ISSUE THREAD

**Issue by tommoor** [lgarron/clipboard-polyfill#166]
I thought users of this library should be aware that it causes a memory leak in Firefox as they do not properly garbage collect the clipboard object, although a patch is in the works.

See more details on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1886056

**Comment by lgarron** [comment]
Interesting, thanks for sharing!

Do you know why the `overwrite-globals` version of the library was used? It's generally much better to [use the ponyfill when possible](https://ponyfill.com/).

**Comment by tommoor** [comment]
I do not, presumably for ease though as it's a large codebase and hard to ensure that other engineers are aware of Firefox limitations

**Comment by tommoor** [comment]
This issue is now addressed in Firefox Nightly build, feel free to close it out – I just wanted to make sure that anyone searching would know about the limitation.
