### ISSUE TITLE
clipboard copied "NotAllowedError: Write permission denied."

### ISSUE THREAD

**Issue by jerry-wolf** [lgarron/clipboard-polyfill#167]
Environment: Android WebView (has native async clipboard API, but throws NotAllowedError when called).
Perhaps Promise.protoype.catch call a function with an error instead of a string [here](https://github.com/lgarron/clipboard-polyfill/blob/690b9cd90d9c891806dd50ea68e92c12ef1d2063/src/clipboard-polyfill/implementations/text.ts#L24)?

**Comment by lgarron** [comment]
By Jove, it seems you're right! Should be an easy fix (but maybe not so easy to test).

**Comment by lgarron** [comment]
@jerry-wolf: Thanks for reporting this! Please let me know if `v4.1.0` fixes the issue!
