### ISSUE TITLE
Add support for attachEvent

### ISSUE THREAD

**Issue by wildcatmatt** [lgarron/clipboard-polyfill#23]
I'm having to update a previously working copy-to-clipboard routine to support IE8 and Chrome.  This works great with Chrome but IE8 gives me a "Object doesn't support this property or method" error on addEventListener.  I was able to get it working under IE8 with these fixes:

```
if(document.addEventListener){
    document.addEventListener("copy", function(e) {
      if (_intercept) {
        for (var key in _data) {
          e.clipboardData.setData(key, _data[key]);
        }
        e.preventDefault();
      }
    });
} else if (document.attachEvent){
    document.attachEvent("copy", function(e) {
      if (_intercept) {
        for (var key in _data) {
          e.clipboardData.setData(key, _data[key]);
        }
        e.preventDefault();
      }
    });
}
```

...

```
if (document.addEventListener) {
    document.addEventListener("paste", function(e) {
      if (_intercept) {
        _intercept = false;
        e.preventDefault();
        var resolve = _resolve;
        _resolve = null;
        resolve(e.clipboardData.getData(_dataType));
      }
    });
} else if (document.attachEvent) {
    document.attachEvent("paste", function(e) {
      if (_intercept) {
        _intercept = false;
        e.preventDefault();
        var resolve = _resolve;
        _resolve = null;
        resolve(e.clipboardData.getData(_dataType));
      }
    });
}
```

I hope that's helpful.

**Comment by lgarron** [comment]
Why not just run `document.addEventListener = document.addEventListener || document.attachEvent;` before anything that attaches an event listener?

**Comment by lgarron** [comment]
I merged #24.

What happens in IE8 if you use document.attachEvent? Anything useful?

**Comment by danchr** [comment]
> What happens in IE8 if you use document.attachEvent? Anything useful compared to not loading?

Doubtful, as `document.execCommand` [isn't supported](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) by IE8.

If you consider how much that browser sucks, and combine it with the fact that Microsoft will drop support for it in less than a month, I'd say there isn't much point in trying to do better. Anyone wanting programmatic copy/paste in IE8 should look into ZeroClipboard or something similar.

**Comment by wildcatmatt** [comment]
When I use document.attachEvent, everything works as I would expect, but to be fair I'm not actually using IE8.

I'm using IE11, but the site I'm working with has the X-UA-Compatible flag set to IE=8, so it still errors due to the mode.

**Comment by lgarron** [comment]
> Doubtful, as document.execCommand isn't supported by IE8.

However, the Promise API would still return failure the same way as a rejected event.

**Comment by danchr** [comment]
> I'm using IE11, but the site I'm working with has the X-UA-Compatible flag set to IE=8, so it still errors due to the mode.

Please note that this is insufficient: The only way to test that code works in IE8 is to actually run it in IE8 — emulation isn't quite the same.

> However, the Promise API would still return failure the same way as a rejected event.

Well, considering that it would be too late to use something like ZeroClipboard, that would be of little value. Personally, I'd prefer an API for querying whether 'clipboard.js' actually worked — this would allow me to suppress or hide the relevant UI or fall back to ZeroClipboard without doing my own user agent checking.

**Comment by lgarron** [comment]
We no longer register a listener at library load time. If someone is still having issues with old version of IE, please let me know in a new bug.
