### ISSUE TITLE
Only plain text work in IE

### ISSUE THREAD

**Issue by PetrSnobelt** [lgarron/clipboard-polyfill#25]
I try to copy both richtext and dom node, but both don't work in IE 11

**Comment by lgarron** [comment]
IE doesn't support rich text copying. :-(

**Comment by PetrSnobelt** [comment]
It works in https://github.com/zenorocha/clipboard.js ...

**Comment by lgarron** [comment]
Oh, it does? I assumed that intercepting the copy event would be able to do the same as the selection API. `execCommand` is a mess.

**Comment by lgarron** [comment]
I don't intend to support an API that takes a DOM element selection.
