### ISSUE TITLE
Doesn't work with Microsoft Edge

### ISSUE THREAD

**Issue by EugenePavlikov** [lgarron/clipboard-polyfill#33]

**Comment by ilyaGurevich** [comment]
Any follow up on this?

**Comment by lgarron** [comment]
I don't have time to look into this, but I'd be happy to look at a pull request.

**Comment by CestDiego** [comment]
I get a `Promise` is not defined in Edge

**Comment by lgarron** [comment]
> I get a Promise is not defined in Edge

I don't have access to a VM with Edge right now.
The code contains a polyfill for Promise, but Edge might not hit the correct code path due to broken feature detection.

Two questions:
- Which commit of the code are you using (and are you using the minified version)?
- Where in the code does the error occur?

**Comment by CestDiego** [comment]
@lgarron sorry for the late response.

- I'm using the version from npm so I don't know which commit it has.
- This is where the error starts:
![image](https://cloud.githubusercontent.com/assets/3291619/21656746/5b762d22-d28d-11e6-8ffb-71947d8a2449.png)

Error is 

![image](https://cloud.githubusercontent.com/assets/3291619/21656776/7ba1910e-d28d-11e6-88a2-f4866709d18f.png)

**Comment by mhuggins** [comment]
Ahh, not having this capability is a deal-breaker.  This looked like a good option, otherwise!

**Comment by ryantheleach** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/promiseses6/?q=promise

Claims that promises are supported.

**Comment by lgarron** [comment]
Edge should work as of `v2.0.0`.
