### ISSUE TITLE
Avoid loading Promise polyfill in modern browsers.

### ISSUE THREAD

**Issue by lgarron** [lgarron/clipboard-polyfill#59]
It's only needed on IE. :-/

Instead of pretty native `Promise`, I see the polyfill even in Chrome right now.

**Comment by the-spyke** [comment]
Just bumped into this issue when I was trying to debug `.writeText(...).finally is not a function` error.

**Comment by lgarron** [comment]
Yeah, I wish there were a simple solution. Open to (compatible) suggestions.

**Comment by the-spyke** [comment]
I'd suggest to build without polyfills and let users use their own if they need it. Just add to `readme` what ES2015+ features this library requires.

**Comment by lgarron** [comment]
The main point of this library is to be as compatible as possible with old browsers while the new API is rolling out. I don't feel comfortable removing compatibility with IE by default, although I'm okay with users opting out of the polyfill.

**Comment by lgarron** [comment]
99de8118ef47ec8d29750ca8e49d6e1e1b246020 is not super-clean, but it passes the type checks and avoids using `es6-promise` in browser that already have `Promise`.

I would prefer not to support multiple builds unless there are specific concerns about that, so hopefully that will do for now.
