### ISSUE TITLE
Type definition

### ISSUE THREAD

**Issue by buu700** [lgarron/clipboard-polyfill#61]
I was about to file a report with DefinitelyTyped about creating a @types/clipboard-polyfill based on @types/clipboard-js, but since this is now already in TypeScript, it looks like that shouldn't even be necessary!

You can achieve the same thing here with `tsc --declaration clipboard-polyfill.ts` and adding `"types": "./clipboard-polyfill.d.ts"` to package.json, which printed a few errors (copied below) but otherwise seems to work as expected.

```
DT.ts(7,40): error TS2693: 'Map' only refers to a type, but is being used as a value here.
DT.ts(10,26): error TS2339: Property 'has' does not exist on type 'Set<string>'.
DT.ts(14,12): error TS2339: Property 'set' does not exist on type 'Map<string, string>'.
DT.ts(18,19): error TS2339: Property 'get' does not exist on type 'Map<string, string>'.
DT.ts(23,19): error TS2339: Property 'forEach' does not exist on type 'Map<string, string>'.
DataType.ts(6,48): error TS2693: 'Set' only refers to a type, but is being used as a value here.
DataType.ts(8,18): error TS2339: Property 'add' does not exist on type 'Set<string>'.
```

**Comment by lgarron** [comment]
Thanks!

I don't know if I'll have time for this in the near future, but I'd be excited to see a PR for it!

**Comment by buu700** [comment]
Sounds good, done! (Sorry, would've just submitted this as a PR to begin with if I'd noticed that `declaration` could just be added to tsconfig.json instead of trying to figure out where in the Makefile to put that `tsc --declaration` line.)
