### ISSUE TITLE
Copy clip not working first run for async load clipboard.js

### ISSUE THREAD

**Issue by lolipop99** [lgarron/clipboard-polyfill#65]
```javascript
$.getScript('https://garron.net/code/clipboard-polyfill/build/clipboard-polyfill.js', function(){
  clipboard.writeText("This text is plain.");        
})
```

It doesn't work,`clipboard.writeText("This text is plain.");` one more time it work. @lgarron

**Comment by lgarron** [comment]
From a first glance, it looks like you're trying to load @zenorocha's clipboard library, and then calling this library once it has loaded. You should pick one or the other. ;-)

If you're trying to use this library, can you modify [this writeText example](https://github.com/lgarron/clipboard-polyfill/blob/0b84df8d0eff7a8b642143e03166c95a9f1b212a/index.html#L32) to suit your needs?

If you're using `clipboard-polyfill`, make sure to call `clipboard.writeText()` directly in an event handler for a user gesture (e.g. a click).

If you wait for an AJAX call to respond, then the browser won't consider your copy action to be triggered by the last user gesture, and block it. (Chrome has a 1-second grace period for this. If your code runs twice and the second request returns from the cache in less than a second, this may explain the behaviour where it succeeds only the second time).

**Comment by lolipop99** [comment]
sorry.the library address has just been wrongly written.

I can't make it work by rewriting your example
```javascript
$('.txt').on('click', function(){
$.getScript('https://garron.net/code/clipboard-polyfill/build/clipboard-polyfill.js', function(){
  clipboard.writeText("This text is plain.").then(function(){
                            console.log('success');
                        }, function(err){
                            console.log('error')
                        });    
})
})
```
@lgarron

**Comment by lgarron** [comment]
If you're using jQuery, you should do this:

    <script src="jquery-3.2.1.min.js"></script>
    <script src="clipboard-polyfill.js"></script>
    <button id="copyBtn">Click me!</button>
    <script>
    $("#copyBtn").on("click", function() {
      clipboard.writeText("test");
    });
    </script>

Please make sure you don't load the code directly from `garron.net`. It is not a CDN, so it is not designed to take a heavy load. (You should assume that any code you try to load from it may break at any time.)

Hosting your own copy of the file is safest. :-)
If you need to load the file from the web for testing, I suggest using `https://rawgit.com/lgarron/clipboard-polyfill/master/build/clipboard-polyfill.js`. If you want to load from the web long-term, I suggest trying to use a CDN. `cdnjs` is apparently considering adding it at https://github.com/cdnjs/cdnjs/pull/11995

**Comment by lgarron** [comment]
Have you been able to get this to work? :-)

**Comment by lolipop99** [comment]
I'm sorry, the sample I provided is not accurate enough, it's a waste of your energy. sorry about it.
I have to strengthen my English skills.

The `clipboard-polyfill.js` file is already in my CDN.

I know this way is to work
```javascirpt
<script src="jquery-3.2.1.min.js"></script>
<script src="clipboard-polyfill.js"></script>
<button id="copyBtn">Click me!</button>
<script>
$("#copyBtn").on("click", function() {
  clipboard.writeText("test");
});
</script>
```

But if the file is loaded on demand, it doesn't work first click.
```javascirpt
<script src="jquery-3.2.1.min.js"></script>
<button id="copyBtn">Click me!</button>
<script>
$("#copyBtn").on("click", function() {
  if (typeof clipboard == 'function'){
    clipboard.writeText("second click");
  } else {
    $.getScript('clipboard-polyfill.js', function(){
        clipboard.writeText("first click");
    })
  }
});
</script>
```

**Comment by lgarron** [comment]
> But if the file is loaded on demand, it doesn't work first click.

This is expected. Loading the script on demand incurs a delay, and you need copy to the clipboard without delay from your event handler.

If you want to be able to copy on the first click, you'll have to load the script ahead of time.
