### ISSUE TITLE
Always pastes text/plain content, never text/html

### ISSUE THREAD

**Issue by JohnnyRacket** [lgarron/clipboard-polyfill#68]
I have tested it in Chrome 62 and IE11, if I ever set a text/plain then I will never get the markup/html version. However, if I only set the text/html, it will work correctly from both, other than not being able to paste into plain text fields. Not sure what is supposed to happen, but I think its not correct behavior that it is falling back every time, even though the html can work. Nice work though :)

**Comment by lgarron** [comment]
What happens at https://garron.net/code/clipboard-polyfill/ if you click on "Copy test (markup)" and then paste into the Paste area?

**Comment by JohnnyRacket** [comment]
Hey, it does indeed work, just tested it locally hosted in a plain html file and it worked also, seems to only have issues inside my angular 1.6 application, I am thinking angular is hijacking something and not allowing it to set 2 data types to the clipboard for some reason.

**Comment by lgarron** [comment]
Alright. Good luck! :-)
