### ISSUE TITLE
More nuances to clipboard handling.

### ISSUE THREAD

**Issue by alecazam** [lgarron/clipboard-polyfill#70]
These were tested on Windows 10.  Just thought I'd share some of my observations.  There is way too much nuance to getting data to the clipboard with the existing, broken APIs.  Thank you for documenting so many of the details!  I wish I'd found your polyfill before finding similar solutions.

1. Chrome crashes with an "aw snap" if you try to call e.clipboard.setData("text/plain", data) with data.length > 60MB.  Firefox/Edge don't crash.

2. Chrome/FF/Edge have a watchdog timer.  I've measured this at a 1s on Chrome.  Formatting 6MB of ascii text (from an SVG) takes around 30s.  So if you generate an export, pass the string to a hidden textArea, and then select() that.  Ignoring the time to export (which can be many seconds) leaves you with an always failed execCommand('copy') afterwards.

You have to perform the export and setData() calls within the 'copy' listener.  Then the watchdog timer doesn't seem to apply.  So run execCommand as quickly as possible, then take your time.

3. Formatting a hidden text area with 100MB takes around 100s.  This freezes up the browser while this happens, and users think the web app has crashed. 

There doesn't seem to be a way to:
  a. can't provide progress 
      the export and setData have to occur in the listener, 
      anything else gets killed by the watchdog timer
  b. can't use setTimeout (or it's no longer user-initiated)
  c. can't defer evaluation of clipboard data until client paste
     (key to apps on OSX/Windows/Linux)
 
We've reported these on the new clipboard API spec that you are emulating with this polyfill.

**Comment by lgarron** [comment]
Thanks for reporting that on the new clipboard spec.

I think the best workaround for sites that need to generate data asynchronously is to have the copy button show a spinner that says "Generating..." and then "Ready to copy!"

I don't think there's anything useful for a polyfill to do, though until the new spec has an async mechanism that we can at least partially shim. 😔

**Comment by lgarron** [comment]
> We've reported these on the new clipboard API spec that you are emulating with this polyfill.

I can't find this on https://github.com/w3c/clipboard-apis/issues ; could you post a link for future reference?

**Comment by lgarron** [comment]
> Chrome crashes with an "aw snap" if you try to call e.clipboard.setData("text/plain", data) with data.length > 60MB. Firefox/Edge don't crash.

I've filed a Chromium bug for this: crbug.com/810787

The rest of the issues can only be addressed by a new API.
(As a workaround, you can show a "generating data" message to the user when they first attempt to copy, then notify them to trigger the app's copy action again in order to actually copy the generated data.)
