### ISSUE TITLE
Clipboard-polyfill adding commas

### ISSUE THREAD

**Issue by david-j-davis** [lgarron/clipboard-polyfill#71]
Hello, I'm using a template literal to build my text/html and am getting commas no matter how I write my html when looping over text. This is being added by the polyfill. Observe

Html:

```
let dt = new clipboard.DT();
    dt.setData("text/html",
      `
       <h4>Ingredients:</h4>
       <ul>${recipe.ingredients.ingredient.map(item => `<li>${item.quantity} ${item.measure} ${item.ingredient}</li>`)}</ul>
       <br>
       <h4>Instructions:</h4>
       <p>${recipe.instructions}</p>
      `
    );
    clipboard.write(dt);
```

Output:
<img width="233" alt="screen shot 2017-12-07 at 6 11 01 pm" src="https://user-images.githubusercontent.com/3498223/33747829-0a82ce42-db7a-11e7-83cf-b37420f6755b.png">

**Comment by lgarron** [comment]
Do you have more self-contained reproduction steps?

`clipboard-polyfill` does not attempt to transform the data, so I don't see a reason this should happen.

**Comment by lgarron** [comment]
> clipboard-polyfill does not attempt to transform the data, so I don't see a reason this should happen.

In particular, could you provide the expanded template string that you pass to `dt.setData()` to make sure the comma appears properly there?

**Comment by lgarron** [comment]
*gentle ping*

**Comment by david-j-davis** [comment]
Here's the template string that Im sending to setData()
`dt.setData("text/html",
      `<h1>${recipe.title}</h1>
       <p><strong>${recipe.description}</strong></p>
       <p><strong>Cuisine:</strong> ${recipe.cuisine}</p>
       <p><strong>Source:</strong> ${recipe.source}</p>
       <p><strong>Yield:</strong> ${recipe.yield}</p>
       <br>
       <h4>Ingredients:</h4>
       <ul>${recipe.ingredients.ingredient.map(item => `<li>${item.quantity} ${item.measure} ${item.ingredient}</li>`)}</ul>
       <br>
       <h4>Instructions:</h4>
       <p>${recipe.instructions}</p>
       <br>
       <p>Enjoy for:</p>
       <ul>${recipe.tag.map(item => `<li>${item}</li>`)}</ul>
       <p><small>Recipe provided by <a href='https://myrecipe.zone'>My Recipe Zone</a></small></p>
      `
    );
    clipboard.write(dt);`

And here is a screenshot of the output pasted in an email, and notice how there are commas where the bullet points are, unintended.

Thanks

<img width="373" alt="screen shot 2018-01-10 at 9 39 35 am" src="https://user-images.githubusercontent.com/3498223/34786881-3d3606ee-f5ea-11e7-9230-fca9f821aee7.png">

**Comment by lgarron** [comment]
What does the console print when you do the following?

    str = `<h1>${recipe.title}</h1>
       <p><strong>${recipe.description}</strong></p>
       <p><strong>Cuisine:</strong> ${recipe.cuisine}</p>
       <p><strong>Source:</strong> ${recipe.source}</p>
       <p><strong>Yield:</strong> ${recipe.yield}</p>
       <br>
       <h4>Ingredients:</h4>
       <ul>${recipe.ingredients.ingredient.map(item => `<li>${item.quantity} ${item.measure} ${item.ingredient}</li>`)}</ul>
       <br>
       <h4>Instructions:</h4>
       <p>${recipe.instructions}</p>
       <br>
       <p>Enjoy for:</p>
       <ul>${recipe.tag.map(item => `<li>${item}</li>`)}</ul>
       <p><small>Recipe provided by <a href='https://myrecipe.zone'>My Recipe Zone</a></small></p>
      `;
    console.log(str);
    dt.setData("text/html", str);
    clipboard.write(dt);

**Comment by lgarron** [comment]
I haven't heard back in a month, but happy to reopen if you can produce a self-contained snippet that reproduces the bug.

**Comment by david-j-davis** [comment]
I did respond. On GitHub I believe.

**Comment by lgarron** [comment]
The latest example I have from you is https://github.com/lgarron/clipboard-polyfill/issues/71#issuecomment-356678831 , but that depends on predefined variables for the templates; do you have a flattened HTML string that you believe ends up with extra commas when copied?
