### ISSUE TITLE
Doesn't work in IE<11 due to use of Set API

### ISSUE THREAD

**Issue by phildarnowsky** [lgarron/clipboard-polyfill#72]
https://github.com/lgarron/clipboard-polyfill/blob/be05dad095f68fb32df1b4f5927c3827c86dfd25/DT.ts#L6 `Set` first appears in IE11, so execution in an older version of IE errors out when it hits this line.

**Comment by lgarron** [comment]
Hmm, I don't want to use a polyfill, so I guess we'll have to replace it with a raw object. :-/

**Comment by lgarron** [comment]
Let me know if `v2.3.1` fixes the issue.

**Comment by joeydi** [comment]
This issue also applies to Map.

**Comment by lgarron** [comment]
> This issue also applies to Map, which is still in use in the latest version.

Oh, looks like you're right. *gnarls teeth and digs in*.

**Comment by lgarron** [comment]
Alright, I downloaded the IE9 VM for testing, and it *appears* to work for now, even though https://caniuse.com/#search=console.warn suggests that we should be running into errors when DevTools is closed. Could you test how it works for you?

**Comment by joeydi** [comment]
2.4.1 is working in IE10 now. I haven't been able to test in IE9, and probably won't...

**Comment by lgarron** [comment]
Okay, looks like this is fixed for now. I've filed a bug about a release test plan so we don't regress.
