### ISSUE TITLE
Copy command failed in ios Safari if -webkit-user-select is none for created span

### ISSUE THREAD

**Issue by Amareis** [lgarron/clipboard-polyfill#75]
https://jsfiddle.net/561qcehd/11/
It can be workarounded easily if change css selector for rule to something more specific than `body`, but i think that library should handle this case, e.g. using inline styles for created span with `-webkit-user-select: text;`.

**Comment by lgarron** [comment]
Oh, fun. It should be easy to add `-webkit-user-select: text !important;` inline.

https://github.com/lgarron/clipboard-polyfill/blob/23bb29e9c0bd8b33fb3afb9d99dfbee94a8c8a09/clipboard-polyfill.ts#L182

Do you know how other browsers behave?

**Comment by lgarron** [comment]
So, I thought I had a solution for this, but it doesn't appear to work if `-webkit-user-select: none` is set on the entire body rather than a surrounding element. :-(

**Comment by Amareis** [comment]
You don't need to set `important` for element styles cause it already has max prority. Seem to 2.4.2 worked totally ok on mobile safari, checked in https://jsfiddle.net/561qcehd/12/ (it's jsfiddle from top message, but with 2.4.2 version).

**Comment by lgarron** [comment]
> You don't need to set important for element styles cause it already has max prority.

On my computer, setting `!important` on the element appears to be necessary if the enclosing element also has `!important`.

Thanks for verifying the fix!

**Comment by Amareis** [comment]
Yeah, if global styles has `!important`, it breaks all the things. But even in https://jsfiddle.net/561qcehd/13/ (with global `!important`) all works in mobile safari, so thank you for fix.
