### ISSUE TITLE
Remove Promise polyfill

### ISSUE THREAD

**Issue by invliD** [lgarron/clipboard-polyfill#79]
Instead of bringing in a Promise polyfill, this library should encourage users to bring their own if they need to support old browsers, but shouldn't make this assumption by itself.

In my case I do want that polyfill, but I'm already bringing my own, so this one would just unnecessarily increase my bundle size.

**Comment by lgarron** [comment]
The main point of this library is that it Just Works™️ across as many browsers as possible, so I want IE to work out of the box.

However, I'd be open to a PR with suitably designed way to opt out of shipping a separate polyfill fallback (note that the polyfill is not *used* in modern browsers as of #59, so the main remaining concern should be code bloat), e.g.
- a build that outputs two JS files (in a way such that it's easy to use the correct one), or
- avoids loading the polyfill if the module system can already guarantee one.

Examples of similar projects successfully supporting an optional polyfill like this would be useful to know.

**Comment by rcchen** [comment]
One example of a project that successfully asks people to use their own polyfill is React. From [JavaScript Environment Requirements][js-env] for React:

> React 16 depends on the collection types Map and Set. If you support older browsers and devices which may not yet provide these natively (e.g. IE < 11), consider including a global polyfill in your bundled application, such as core-js or babel-polyfill.

Seems fairly reasonable to have a BYOP (bring your own polyfill) stance if you need to support older browsers or are including your own polyfill already (ie. core-js) and don't need a duplicate.

  [js-env]: https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by crazy4groovy** [comment]
Obligatory status icon required: https://twitter.com/acdlite/status/974390255393505280
