### ISSUE TITLE
Amend `eval` and the `Function` constructor to typeof window == 'undefined' ? typeof global == 'undefined' ? this : global : window

### ISSUE THREAD

**Issue by ryanwhocodes** [lgarron/clipboard-polyfill#83]
When using the clipboard-polyfill.js in a firefox extension and submitting it to https://addons.mozilla.org, the extension Validation Results produced warnings:

> Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
> js/clipboard-polyfill.js line 406
> js/clipboard-polyfill.js line 606

As suggested in this github page: https://github.com/YuzuJS/setImmediate/issues/49

I amended these lines to use the below code instead, which solved the validation issue with the code.
`typeof window == 'undefined' ? typeof global == 'undefined' ? this : global : window`

I propose amending line 406 from:
`            t = Function("return this")()
`
to
`            t = typeof window == 'undefined' ? typeof global == 'undefined' ? this : global : window
`

...and 606 from
     ` n = n || Function("return this")() || (0, eval)("this")`
to:
      `n = n || typeof window == 'undefined' ? typeof global == 'undefined' ? this : global : window`

**Comment by ryandav** [comment]
@lgarron I really like clipboard-polyfill - it's easy to use with a minimal amount of code and saved a lot of pain trying to copy html to the clipboard when writing a browser extension.

I'm be more than happy to submit a PR for this issue if you like

**Comment by ryandav** [comment]
Here's the PR - https://github.com/lgarron/clipboard-polyfill/pull/84

The line numbers were from using Atom beautify - but they're hard to see in the minified version, so I've added both files the PR (to show the changed lines of code).
