### ISSUE TITLE
Allow using the "with Promise" version using es6-promise as an external dependency.

### ISSUE THREAD

**Issue by lgarron** [lgarron/clipboard-polyfill#87]
Right now, the Promise version includes all of `es6-promise` in the build. It would be nice if the polyfill could be shared as a dependency in another project.

**Comment by abraham** [comment]
Wouldn't a developer just use their own Promise polyfill and then use the `clipboard-polyfill` version without the Promise polyfill?

**Comment by lgarron** [comment]
I've restructured the versions so taht this is no longer relevant.
