### ISSUE TITLE
2.5.0 has published a .git file

### ISSUE THREAD

**Issue by nathanpower** [lgarron/clipboard-polyfill#90]
Probably you didn't intend to do this (and it can mess with CI builds). See https://registry.npmjs.org/clipboard-polyfill/-/clipboard-polyfill-2.5.0.tgz

**Comment by lgarron** [comment]
Huh, I didn't have that problem with previous versions. I'm *guessing* this is because I used `npm publish`, because I can't use `yarn publish`: https://github.com/yarnpkg/yarn/issues/4904

**Comment by lgarron** [comment]
Yep, `npm pack` includes the `.git` file, while `yarn pack` doesn't. :-/

Adding `/.git` to `.npmignore` as a workaround seems to work.

**Comment by lgarron** [comment]
Looks like `npm` only ignores `.git` folders, not `.git` files:

https://github.com/npm/npm-packlist/blob/master/index.js#L23

**Comment by lgarron** [comment]
I've filed a bug at https://github.com/npm/npm-packlist/issues/15 and sent a pull request at https://github.com/npm/npm-packlist/pull/16

I'd also love to switch back to `yarn publish` in case there are other bugs waiting, but I'm still waiting on https://github.com/yarnpkg/yarn/issues/4904
