### ISSUE TITLE
2.5.0 failing to require in electron

### ISSUE THREAD

**Issue by solgarius** [lgarron/clipboard-polyfill#93]
Our electron app cannot seem to resolve clipboard-polyfill when it is required.

I am getting the error: `Cannot find module 'clipboard-polyfill'`
May or may not be relevant, but we also use webpack, though we explicitly exclude `node_modules` from our webpack and require them normally in electron so webpack shouldn't matter.

2.4.7 works fine.

To replicate just create an electron app and do in the UI window process:
`let clipboard = require('clipboard-polyfill')`

We are running electron 1.8.2

**Comment by lgarron** [comment]
Thanks for reporting!

I've never created an Electron app; is there a simple template app I can
try this with?

**Comment by lgarron** [comment]
Also, if you have the library locally, could you try reverting the change
in
https://github.com/lgarron/clipboard-polyfill/commit/2de1afd30fe32f8195c198b3c812dd237abcb8e9
to see if that fixes it?

**Comment by lgarron** [comment]
https://electronjs.org/docs/tutorial/first-app#trying-this-example was actually pretty painless. It appears that 2de1afd is indeed incompatible with Electron. Since it doesn't seem to hurt to use `main`, I'll switch back to that.

**Comment by lgarron** [comment]
Okay, I couldn't quite get publishing the way to work that I wanted, but I've published `v0.5.2`. Could you see if that fixes the issue?

**Comment by solgarius** [comment]
@lgarron thanks `v2.5.2` has fixed the issue, running perfectly on electron and in browser.
