### ISSUE TITLE
Add a "modern browser only" build.

### ISSUE THREAD

**Issue by lgarron** [lgarron/clipboard-polyfill#96]
Older versions of Safari and Edge are becoming less relevant, so we can get rid of some workarounds and support a smaller build that has full compatibility with users whose browsers are moderately up to date.

**Comment by Favna** [comment]
Can you specify "modern browsers" further? Considering most modern browsers support `document.execCommand("copy")`

**Comment by lgarron** [comment]
The latest versions of Safari and Edge, based on which of the known issues they've fixed since I made this chart: https://github.com/lgarron/clipboard-polyfill/blob/master/experiment/Conclusions.md#test-results

**Comment by lgarron** [comment]
`clipboard-polyfill` will soon be obsolete for modern browser (come on, Chrome and Firefox!). This library only really helps for compat with older browsers, so I don't intend to add a new build for modern browsers at this point.
