### ISSUE TITLE
Stable browser crash Opera 53.0-55.0

### ISSUE THREAD

**Issue by nike80** [lgarron/clipboard-polyfill#97]
Get stable browser crash Opera 53.0-55.0 when try use clipboard.readText() with any params.

**Comment by lgarron** [comment]
Thanks for the report! I'm looking into it.

**Comment by lgarron** [comment]
I tried to report this bug to Opera via several channels immediately after August 24, but I never heard back. :-(

The latest version of Opera includes enough of the Chrome implementation that it does not crash anymore, so I consider this fixed.
