### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by taikn** [lgarron/clipboard-polyfill#98]
Latest version (2.5.3) throws on attempt to `writeText` in IE11:
```
TypeError: Unable to get property 'setData' of undefined or null reference
```

**Comment by lgarron** [comment]
Hi @taikn,

I can't reproduce with the `Copy text (plain)` button at https://garron.net/code/clipboard-polyfill/ in IE 11.1.171.17134.0 in Windows 10.0 – it copies the text as intended. Could you provide more details on your environment, or which website/code snippet is affected?

**Comment by taikn** [comment]
Hmmm, I am using it in one of my sagas like this:

```javascript

import clipboard from 'clipboard-polyfill'

...

yield call([clipboard, clipboard.writeText], 'some text')

...

```

It invokes `writeText` method passing `this` context and waits for it to resolve/reject.

This works flawless in other browsers, but throws in IE11 (Windows 10) pointing to this line: https://github.com/lgarron/clipboard-polyfill/blob/8d9b7cab7ecdd24d17fcc2b5a3ef39071abd886d/clipboard-polyfill.ts#L140

And I've got all necessary polyfills (Promise etc.) in place - its really confusing, since previous version (2.5.2) works without any issues.

**Comment by taikn** [comment]
Yes! In `v2.5.4` it works back again. Thank you for your time!
